-- Database schema and sample data for Supabase Islamic Quiz

-- Table for questions
create table public.questions (
  id serial primary key,
  question text not null,
  options text[] not null,
  answer integer not null
);

-- Table for user scores
create table public.scores (
  user_id uuid primary key references auth.users(id) on delete cascade,
  score integer not null default 0
);

-- Seed questions
insert into public.questions (question, options, answer) values
('What is the first month of the Islamic calendar?', ARRAY['Muharram', 'Ramadan', 'Rajab', 'Dhul-Hijjah'], 0),
('Who was the last prophet in Islam?', ARRAY['Prophet Musa', 'Prophet Isa', 'Prophet Muhammad', 'Prophet Yusuf'], 2),
('What is the name of the holy book revealed to Prophet Muhammad?', ARRAY['Torah', 'Zabur', 'Injeel', 'Quran'], 3),
('How many daily prayers are obligatory?', ARRAY['Three', 'Four', 'Five', 'Ten'], 2),
('In Ramadan, Muslims fast from?', ARRAY['Morning to Evening', 'Sunrise to Sunset', 'Fajr to Maghrib', 'Dhuhr to Isha'], 2)
('How many daily prayers are there in Islam?', ARRAY['Three', 'Four', 'Five', 'Seven'], 2),
('Who was the first person to accept Islam from men?', ARRAY['Abu Bakr', 'Ali', 'Umar', 'Bilal'], 0),
('In which city was Prophet Muhammad ﷺ born?', ARRAY['Makkah','Madinah','Jerusalem','Baghdad'], 0),
('What is the holy book of Islam called?', ARRAY['Bible','Torah','Quran','Gospel'], 2),
('How many Surahs are in the Qur’an?', ARRAY['114','99','86','120'], 0),
('Who is known as “Khalilullah” (Friend of Allah)?', ARRAY['Ibrahim','Musa','Yusuf','Isa'], 0),
('Which angel brought revelation to the prophets?', ARRAY['Jibril','Israfil','Mikail','Azrael'], 0),
('What is the Islamic pilgrimage to Makkah called?', ARRAY['Zakat','Salah','Hajj','Umrah'], 2),
('Who was the first woman to accept Islam?', ARRAY['Khadijah','Fatimah','Aisha','Maryam'], 0),
('Which Surah is the longest in the Qur’an?', ARRAY['Al-Baqarah','Al-Fatiha','Al-Imran','Al-Nas'], 0),
('How many days are in Ramadan usually?', ARRAY['29','30','27','31'], 1),
('Which direction do Muslims face when praying?', ARRAY['East','West','Kaaba','Jerusalem'], 2),
('Who built the Kaaba with Prophet Ibrahim عليه السلام?', ARRAY['Ismail','Isa','Musa','Yaqub'], 0),
('What is the first pillar of Islam?', ARRAY['Prayer','Fasting','Shahada','Charity'], 2),
('What is the night of power called in Ramadan?', ARRAY['Isra','Miraj','Laylat al-Qadr','Ashura'], 2),
('How many chapters in Qur’an are named after prophets?', ARRAY['4','6','8','13'], 1),
('Which prophet was swallowed by a whale?', ARRAY['Yunus','Musa','Yusuf','Isa'], 0),
('Who was the mother of Prophet Isa عليه السلام?', ARRAY['Fatimah','Maryam','Khadijah','Asiya'], 1),
('Which Surah has only one verse?', ARRAY['Al-Kawthar','Al-Ikhlas','Al-Nas','Al-Fatiha'], 0),
('What is Zakat?', ARRAY['Confession','Charity','Pilgrimage','Prayer'], 1),
('How old was Prophet Muhammad ﷺ when he passed away?', ARRAY['53','63','70','60'], 1),
('Who was the first Caliph of Islam?', ARRAY['Umar','Ali','Abu Bakr','Uthman'], 2),
('What is the Arabic word for charity?', ARRAY['Sadaqah','Hajj','Salat','Qurbani'], 0),
('What does “Islam” mean?', ARRAY['Peace','Submission','Light','Truth'], 1),
('Which Prophet could talk to animals?', ARRAY['Musa','Ibrahim','Sulayman','Yusuf'], 2),
('What is the name of the well in Makkah near the Kaaba?', ARRAY['Beer','Zamzam','Hudaybiyyah','Bayt'], 1),
('Which battle was the first in Islam?', ARRAY['Badr','Uhud','Khandaq','Hunayn'], 0),
('What is the name of Prophet Muhammad’s ﷺ father?', ARRAY['Abdullah','Abdul Muttalib','Abu Talib','Hamza'], 0),
('Which Prophet was known for his wisdom?', ARRAY['Sulayman','Musa','Isa','Ibrahim'], 0),
('Which Surah is often recited for protection?', ARRAY['Al-Baqarah','Al-Falaq','Al-Qadr','Al-Masad'], 1),
('Who was the Prophet’s ﷺ wife known as “Mother of the Believers”?', ARRAY['Khadijah','Aisha','Hafsa','Zainab'], 1),
('What is the holy night journey called?', ARRAY['Isra and Miraj','Hijrah','Qiyam','Fajr'], 0),
('Which animal did Prophet Muhammad ﷺ ride during the night journey?', ARRAY['Camel','Horse','Buraq','Elephant'], 2),
('Which Prophet split the sea by Allah’s command?', ARRAY['Musa','Isa','Yunus','Ibrahim'], 0),
('What is the name of Prophet Muhammad’s ﷺ mother?', ARRAY['Amina','Fatimah','Khadijah','Sofia'], 0),
('What is the term for the Islamic call to prayer?', ARRAY['Adhan','Iqamah','Khutbah','Takbir'], 0),
('The Quran was first revealed in which cave?', ARRAY['Thawr','Hira','Safa','Marwah'], 1),
('What is the shortest Surah in the Qur’an?', ARRAY['Al-Kawthar','Al-Fatiha','Al-Nas','Al-Asr'], 0),
('How many rakahs are there in Fajr prayer?', ARRAY['2','4','3','1'], 0),
('What is the Islamic word for fasting?', ARRAY['Sadaqah','Sawm','Hajj','Tahajjud'], 1),
('What is the language of the Qur’an?', ARRAY['Arabic','Hebrew','Urdu','Persian'], 0),
('Which angel is responsible for blowing the trumpet on the Day of Judgment?', ARRAY['Jibril','Israfil','Mikail','Azrael'], 1),
('Who is the angel of death?', ARRAY['Israfil','Mikail','Azrael','Jibril'], 2),
('Which prophet was known for his patience?', ARRAY['Ayyub','Yusuf','Musa','Isa'], 0),
('What is the day of Jumu’ah equivalent to?', ARRAY['Sunday','Friday','Saturday','Monday'], 1),
('Which Prophet was born without a father?', ARRAY['Isa','Musa','Yusuf','Ibrahim'], 0),
('How many names does Allah have according to Sunnah?', ARRAY['72','99','100','80'], 1),
('Where did the Hijrah take place from and to?', ARRAY['Makkah to Madinah','Taif to Makkah','Jerusalem to Madinah','Madinah to Yemen'], 0),
('Which Surah was revealed completely in one night?', ARRAY['Al-Qadr','Al-Qamar','Al-Mulk','Al-Fatiha'], 0),
('What is the name of the tree in Jannah that has huge shade?', ARRAY['Sidr','Tooba','Zaqqum','Olive'], 1),
('Which Prophet built the Ark?', ARRAY['Nuh','Ibrahim','Musa','Isa'], 0),
('What is the reward for fasting on the day of Ashura?', ARRAY['Forgiveness of previous year','Paradise','Wealth','Extra prayers'], 0),
('What is the name of the Islamic lunar calendar’s first month?', ARRAY['Muharram','Ramadan','Rajab','Dhul-Hijjah'], 0),
('Which Surah is known as “the heart of the Qur’an”?', ARRAY['Ya-Sin','Al-Fatiha','Al-Baqarah','Al-Kahf'], 0),
('Which angel is in charge of rain?', ARRAY['Israfil','Mikail','Jibril','Azrael'], 1),
('What is the holy city Muslims visit on Hajj?', ARRAY['Makkah','Madinah','Jerusalem','Baghdad'], 0),
('Who was the first martyr in Islam?', ARRAY['Sumayyah','Hamza','Bilal','Khadijah'], 0),
('What is the main source of Islamic law after the Qur’an?', ARRAY['Sunnah','Hadith','Ijtihad','Qiyas'], 0),
('What is the place between Jannah and Jahannam called?', ARRAY['Barzakh','Araf','Sijjin','Makaan'], 1),
('Which Prophet interpreted dreams?', ARRAY['Yusuf','Musa','Isa','Nuh'], 0),
('In which month was the Prophet ﷺ born?', ARRAY['Rabi al-Awwal','Ramadan','Dhul-Hijjah','Muharram'], 0),
('Which animal is allowed for Qurban on Eid?', ARRAY['Pig','Goat','Donkey','Dog'], 1),
('Which Prophet had the miracle of healing the blind and sick by Allah’s will?', ARRAY['Isa','Musa','Ibrahim','Yusuf'], 0),
('What is the Islamic term for lawful/permissible?', ARRAY['Haram','Halal','Makruh','Mustahab'], 1),
('What is the last Surah of the Qur’an?', ARRAY['Al-Ikhlas','Al-Nas','Al-Falaq','Al-Baqarah'], 1),
('Who will blow the trumpet on Qiyamah?', ARRAY['Jibril','Israfil','Mikail','Azrael'], 1),
('Which Prophet was raised to heaven alive?', ARRAY['Isa','Yusuf','Sulayman','Musa'], 0),
('Which two prayers are always spoken aloud by the Imam?', ARRAY['Fajr & Maghrib','Dhuhr & Asr','Maghrib & Isha','Asr & Isha'], 2),
('What do Muslims say when they sneeze?', ARRAY['Mashallah','Alhamdulillah','Subhanallah','Jazakallah'], 1),
('What does “Sunnah” mean?', ARRAY['Obligation','Tradition/practice','Prayer','Charity'], 1),
('Which city is called the City of the Prophet ﷺ?', ARRAY['Madinah','Makkah','Baghdad','Cairo'], 0),
('Which Prophet was thrown into fire?', ARRAY['Ibrahim','Isa','Musa','Yusuf'], 0),
('Which Surah mentions Ramadan by name?', ARRAY['Al-Baqarah','Al-Mulk','Al-Qadr','Al-Fatiha'], 0),
('Who was the first young boy to accept Islam?', ARRAY['Ali','Umar','Bilal','Zaid'], 0),
('Which Prophet’s father and uncle tried to kill him?', ARRAY['Ibrahim','Isa','Yusuf','Musa'], 2),
('How many wives did Prophet Muhammad ﷺ have?', ARRAY['Four','Two','Eleven','Seven'], 2),
('What is the Arabic term for pilgrimage?', ARRAY['Hajj','Umrah','Sadaqah','Salat'], 0),
('What is the name of the angel who records good deeds?', ARRAY['Raqib','Atid','Israfil','Mikail'], 0),
('What is the name of the angel who records bad deeds?', ARRAY['Atid','Raqib','Israfil','Jibril'], 0),
('What is the name of the pond where believers will drink on Judgment Day?', ARRAY['Kawthar','Zamzam','Salsabil','Tasnim'], 0),
('What is the name of the mountain where the first revelation came?', ARRAY['Hira','Thawr','Uhud','Arafat'], 0),
('What day is Eid al-Adha celebrated?', ARRAY['10th Muharram','10th Dhul-Hijjah','1st Ramadan','1st Shawwal'], 1),
('How many years did Prophet Muhammad ﷺ spend in Makkah after prophethood?', ARRAY['10','13','23','20'], 1),
('What is the place where Prophet Muhammad ﷺ is buried?', ARRAY['Makkah','Madinah','Jerusalem','Taif'], 1),
('Which Prophet spoke when he was a baby?', ARRAY['Isa','Musa','Yunus','Ibrahim'], 0),
('Which Prophet made a dua that turned into Surah Al-Falaq and Surah An-Naas?', ARRAY['Muhammad','Musa','Yusuf','Ibrahim'], 0),
('What is the Arabic word for the testimony of faith?', ARRAY['Shahada','Salam','Sadaqah','Zakat'], 0),
('Which country did the first Muslims migrate to before Madinah?', ARRAY['Persia','India','Abyssinia','Egypt'], 2),
('Which Surah is named after a woman?', ARRAY['Maryam','Aisha','Hawa','Fatimah'], 0),
('What is the special prayer performed during Ramadan nights?', ARRAY['Tahajjud','Tarawih','Witr','Dhuha'], 1),
('Who was the Prophet’s ﷺ cousin who later became the fourth Caliph?', ARRAY['Ali','Umar','Abu Bakr','Uthman'], 0),
('What is the number of obligatory fasts in a year?', ARRAY['30','29/30','12','2'], 1),
('Who were the two best friends buried beside Prophet Muhammad ﷺ?', ARRAY['Ali & Uthman','Abu Bakr & Umar','Hamza & Bilal','Khadijah & Fatimah'], 1),
('Which angel will question people in their graves?', ARRAY['Munkar & Nakir','Jibril & Mikail','Israfil & Atid','Azrael & Raqib'], 0),
('What is the Arabic word for “paradise”?', ARRAY['Jannah','Jahannam','Barzakh','Sadaqah'], 0),
('What is the Arabic word for “hellfire”?', ARRAY['Jahannam','Jannah','Barzakh','Mustahab'], 0),
('Which Surah is the last Surah revealed in the Qur’an according to many scholars?', ARRAY['Al-Nasr','Al-Falaq','Al-Nas','Al-Takwir'], 0),
('How many Makki Surahs are in the Qur’an?', ARRAY['86','28','56','99'], 0),
('Which Prophet is mentioned the most times in the Qur’an?', ARRAY['Musa','Muhammad','Isa','Ibrahim'], 0),
('What is the longest Ayah in the Qur’an?', ARRAY['Ayat ul Kursi','Verse of loan (Al-Baqarah 282)','First verse of Al-Baqarah','Al-Fatiha'], 1),
('Which Prophet’s people were punished by stones of baked clay?', ARRAY['Lut','Nuh','Hud','Shuayb'], 0),
('Which Sahabi wrote the Treaty of Hudaybiyyah?', ARRAY['Ali','Umar','Zayd ibn Thabit','Uthman'], 0),
('Which battle is known as the turning point after Uhud?', ARRAY['Battle of Khandaq','Battle of Badr','Battle of Tabuk','Battle of Hunayn'], 0),
('What was the age of Prophet Muhammad ﷺ at the time of Hijrah?', ARRAY['53','40','25','60'], 0),
('In which year of Hijrah was Salah made obligatory?', ARRAY['2nd','1st','3rd','5th'], 1),
('Which Surah must be recited in every Rak’ah of Salah?', ARRAY['Al-Fatiha','Al-Baqarah','Al-Ikhlas','Al-Mulk'], 0),
('Who was the foster mother of Prophet Muhammad ﷺ besides Halimah?', ARRAY['Thuwaybah','Fatimah','Khadijah','Maryam'], 0),
('Which Prophet was given the miracle of reviving the dead by Allah’s permission?', ARRAY['Isa','Musa','Ibrahim','Yusuf'], 0),
('Who led the Muslims in the Battle of Yarmouk?', ARRAY['Khalid ibn al-Walid','Ali','Umar','Hamza'], 0),
('What is the Islamic ruling on using gold utensils for men and women?', ARRAY['Allowed','Forbidden','Mustahab','Makruh'], 1),
('Which angel was sent to punish the people of Prophet Lut عليه السلام?', ARRAY['Jibril','Israfil','Azrael','Mikail'], 0),
('What is the Arabic name of the Horn that will be blown on Qiyamah?', ARRAY['Sur','Nafkh','Qasab','Fajr'], 0),
('Which Surah is called “Ummul Kitab” by some scholars due to rulings?', ARRAY['Al-Fatiha','Al-Baqarah','An-Nisa','Al-Imran'], 1),
('What does “Tawheed al-Rububiyyah” refer to?', ARRAY['Allah’s Oneness in Worship','Oneness in Lordship','Oneness in Names','Belief in Angels'], 1),
('Which prophet’s son drowned in the great flood?', ARRAY['Nuh','Musa','Ibrahim','Isa'], 0),
('Which Surah does not contain the letter ب (ba)?', ARRAY['Al-Kawthar','Al-Fatiha','Al-Ikhlas','Al-Qadr'], 2),
('Who was given the title “As-Siddiq”?', ARRAY['Umar','Ali','Abu Bakr','Uthman'], 2),
('Who will be the first person to be clothed on the Day of Judgment?', ARRAY['Ibrahim','Muhammad','Musa','Isa'], 0),
('Which Prophet’s wife turned against him and is mentioned in the Qur’an?', ARRAY['Nuh','Ibrahim','Yusuf','Musa'], 0),
('Which companion is titled “The Sword of Allah”?', ARRAY['Umar','Ali','Khalid ibn al-Walid','Hamza'], 2),
('What is the name of the battle where the trench was dug?', ARRAY['Battle of Khandaq','Battle of Hunayn','Battle of Tabuk','Battle of Badr'], 0),
('Which prophet is mentioned by name only once in the Qur’an?', ARRAY['Harun','Idris','Yaqub','Shuayb'], 1),
('Who was appointed commander in the Battle of Mu’tah after three martyrs?', ARRAY['Khalid ibn al-Walid','Ali','Umar','Uthman'], 0),
('What is the first deed judged on the Day of Judgment?', ARRAY['Zakat','Prayer (Salah)','Hajj','Fasting'], 1),
('Which Surah describes the Throne (Arsh) of Allah extensively?', ARRAY['Al-Baqarah','Al-Muminun','Al-Mulk','Al-Isra'], 2),
('In which Surah is the story of Dhul-Qarnayn mentioned?', ARRAY['Al-Kahf','Al-Baqarah','Al-Imran','Al-Maidah'], 0),
('How many nights did Prophet Musa عليه السلام spend at Mount Sinai?', ARRAY['30','10','20','40'], 3),
('What is the name of the Isra’ wal Mi’raj event’s winged creature?', ARRAY['Buraq','Pegasus','Horse','Camel'], 0),
('Who will be the last person to enter Paradise?', ARRAY['A poor believer','A king','A martyr','A Prophet'], 0),
('Which Prophet was given knowledge of the unseen by listening to creatures?', ARRAY['Sulayman','Musa','Ibrahim','Nuh'], 0),
('Which Surah is called “The Protector” from the grave punishment?', ARRAY['Al-Mulk','Al-Fatiha','Al-Baqarah','Al-Qadr'], 0),
('What is the punishment for theft in Islamic law?', ARRAY['Exile','Fining','Amputation of hand','Imprisonment'], 2),
('Which Prophet was born from an elderly mother after much dua?', ARRAY['Ishaq','Musa','Yusuf','Isa'], 0),
('What is the name of the treaty that ended the Battle of the Trench siege?', ARRAY['Treaty of Hudaybiyyah','Treaty of Aqabah','Treaty of Taif','Treaty of Medina'], 0),
('Which Prophet’s father, grandfather, and son were also Prophets?', ARRAY['Ibrahim','Yaqub','Isa','Nuh'], 1),
('Who was the Prophet ﷺ’s scribe for most Qur’an revelations?', ARRAY['Zayd ibn Thabit','Ali','Umar','Uthman'], 0),
('Which Prophet had 12 sons?', ARRAY['Ibrahim','Yusuf','Yaqub','Musa'], 2),
('Which two Surahs are called “Al-Mu’awwidhatayn”?', ARRAY['Al-Falaq & Al-Nas','Al-Baqarah & Al-Fatiha','Al-Kawthar & Al-Ikhlas','Al-Qadr & Al-Takathur'], 0),
('Who conquered Egypt during the time of Umar رضي الله عنه?', ARRAY['Khalid ibn al-Walid','Amr ibn al-As','Ali','Uthman'], 1),
('What is the drink given to believers in Paradise that causes no headache?', ARRAY['Wine of Paradise','Zamzam','Tasnim','Milk'], 0),
('Which Prophet fasted every alternate day?', ARRAY['Dawud','Musa','Isa','Ibrahim'], 0),
('What is the name of the woman who defended the Prophet ﷺ in Uhud and got many wounds?', ARRAY['Sumayyah','Nusaybah bint Ka’ab','Aisha','Fatimah'], 1),
('Which Sahabi was known as the most knowledgeable in inheritance laws?', ARRAY['Zayd ibn Thabit','Abu Bakr','Ali','Umar'], 0),
('Which Surah has two Basmala (بِسْمِ اللّٰهِ) in it?', ARRAY['Al-Naml','Al-Fatiha','Al-Baqarah','Al-Qadr'], 0),
('Which Prophet was skilled in metalwork and armor?', ARRAY['Dawud','Musa','Isa','Ibrahim'], 0),
('Who suggested digging the trench in the Battle of Ahzab?', ARRAY['Salman al-Farsi','Ali','Abu Bakr','Umar'], 0),
('How many letters does the Qur’an approximately contain?', ARRAY['323000','200000','114000','500000'], 0),
('What day of the week will Qiyamah occur on?', ARRAY['Friday','Tuesday','Monday','Sunday'], 0),
('Which Prophet lived the longest lifespan on earth?', ARRAY['Nuh','Adam','Ibrahim','Isa'], 0),
('In which month was the Battle of Badr fought?', ARRAY['Ramadan','Muharram','Rajab','Dhul Hijjah'], 0),
('Who was the first child born to Muslims in Madinah after Hijrah?', ARRAY['Abdullah ibn Zubair','Ali','Usama','Umar'], 0),
('Which Surah contains Ayat-ul-Kursi?', ARRAY['Al-Baqarah','Al-Kahf','Al-Fatiha','Al-Ikhlas'], 0),
('Who was the flag bearer at the conquest of Makkah?', ARRAY['Ali','Umar','Abu Bakr','Hamza'], 0),
('Where will Prophet Isa عليه السلام descend at the end of times?', ARRAY['Masjid al-Aqsa','White Minaret in Damascus','Kaaba','Jannah'], 1),
('Which Surah mentions the spider’s web?', ARRAY['Al-Ankabut','Al-Baqarah','Al-Falaq','Al-Qadr'], 0),
('Which Tafsir is considered the most authentic classical Tafsir by many scholars?', ARRAY['Tafsir al-Tabari','Tafsir al-Jalalayn','Tafsir Ibn Kathir','Tafsir Qurtubi'], 2),
('What is the name of Prophet Musa’s عليه السلام father-in-law?', ARRAY['Shuayb','Lut','Yaqub','Ibrahim'], 0),
('Which Prophet’s people were punished with loud sound (scream)?', ARRAY['Salih','Nuh','Ibrahim','Isa'], 0),
('Which Sahabi compiled the Qur’an into a single Mushaf first?', ARRAY['Zayd ibn Thabit','Umar','Uthman','Ali'], 0),
('What is the name of the well from which the Prophet ﷺ spat into and improved its water?', ARRAY['Well of Quda','Well of Zamzam','Well of Rawha','Well of Tabuk'], 2),
('Which Prophet was the nephew of Prophet Lut عليه السلام?', ARRAY['Ibrahim','Isa','Yaqub','Ishaq'], 0),
('Which Surah is written on the gates of Jannah according to Hadith?', ARRAY['Al-Zalzalah','Al-Nas','Al-Fatiha','Al-Mulk'], 2),
('What is the second source of Islamic law after Qur’an?', ARRAY['Sunnah','Fiqh','Hadith','Ijma'], 0),
('Which Surah was revealed to console the Prophet ﷺ after boycott in Shi’b Abi Talib?', ARRAY['Al-Duha','Al-Mulk','Al-Nas','Al-Kahf'], 0),
('Which animal did the Prophet ﷺ forbid eating because it feeds on filth?', ARRAY['Horse','Hyena','Crow','Pig'], 2),
('Who was the only Sahabi mentioned by name in the Qur’an?', ARRAY['Zayd','Ali','Umar','Abu Bakr'], 0),
('What is the name of the river in Jannah gifted to Prophet Muhammad ﷺ?', ARRAY['Kawthar','Tasnim','Salsabil','Rawdah'], 0),
('During which battle did the angels fight alongside the Muslims?', ARRAY['Badr','Uhud','Hunayn','Khandaq'], 0),
('Which Surah was revealed when the Prophet ﷺ was accused of being abandoned?', ARRAY['Al-Duha','Al-Falaq','Al-Maun','Al-Kawthar'], 0),
('Which companion narrated the most Hadith?', ARRAY['Abu Hurairah','Aisha','Ali','Umar'], 0),
('What is the punishment for adultery for married individuals in Islamic law?', ARRAY['Execution','Stoning','Imprisonment','Flogging'], 1),
('Which Prophet was thrown into a whale’s stomach?', ARRAY['Yunus','Musa','Isa','Ibrahim'], 0),
('Which Surah did Umar رضي الله عنه hear that led him to accept Islam?', ARRAY['Al-Taha','Al-Baqarah','Al-Fatiha','Al-Kahf'], 0),
('What is the meaning of “As-Sab’ul Mathani”?', ARRAY['Seven oft-repeated verses','Great reward','Charity','Patience'], 0),
('Which Surah is named after a type of fruit in Jannah?', ARRAY['Al-Tin','Al-Baqarah','Al-Falaq','Al-Ankabut'], 0),
('What city will be the gathering place on the Day of Judgment?', ARRAY['Jerusalem','Makkah','Madinah','Baghdad'], 0),
('What is the greatest sin in Islam?', ARRAY['Shirk','Murder','Stealing','Disobeying parents'], 0),
('Who was the youngest wife of Prophet Muhammad ﷺ?', ARRAY['Aisha','Khadijah','Hafsa','Sauda'], 0),
('Which Surah discusses the creation of man from a clot?', ARRAY['Al-Alaq','Al-Falaq','Al-Baqarah','Al-Kafirun'], 0),
('Which country did the last Abbasid Caliph rule from?', ARRAY['Egypt','Iraq','Turkey','Syria'], 0),
('What is the name of the angel who controls wind?', ARRAY['Mikail','Israfil','Azrael','Jibril'], 0),
('Which Surah was the first to be revealed completely?', ARRAY['Al-Fatiha','Al-Qalam','Al-Kawthar','Al-Mulk'], 0),
('What is the Arabic term for the obligatory charity paid during Ramadan?', ARRAY['Zakat','Sadaqat','Zakat al-Fitr','Qurban'], 2),
('Who was the first female martyr in Islam?', ARRAY['Sumayyah','Fatimah','Khadijah','Maryam'], 0),
('Which Prophet’s staff turned into a snake?', ARRAY['Musa','Isa','Sulayman','Ibrahim'], 0),
('Which Surah warns against backbiting by mentioning flesh of a dead brother?', ARRAY['Al-Hujurat','Al-Qalam','Al-Kahf','Al-Maida'], 0),
('Which Prophet is buried inside Masjid al-Aqsa according to many narrations?', ARRAY['Sulayman','Ibrahim','Isa','Yusuf'], 0),
('What is the name of the Prophet ﷺ’s wet-nurse from Madinah after Hijrah?', ARRAY['Halimah','Thuwaybah','Umm Ayman','Sofia'], 2),
('Which Sahabi was known for extreme generosity and called “Ghani”?', ARRAY['Uthman','Ali','Umar','Abu Bakr'], 0),
('Which Surah mentions the story of the Companions of the Cave?', ARRAY['Al-Kahf','Al-Isra','Al-Mulk','Al-Falaq'], 0),
('What is the distance of traveling required to shorten prayers in Islam (approx.)?', ARRAY['48 miles','25 miles','80 miles','5 miles'], 2),
('Who was the leader of Quraysh in the Battle of Uhud?', ARRAY['Abu Sufyan','Abu Bakr','Khalid ibn al-Walid','Abu Talib'], 0),
('Which Surah begins with “Iqra’”?', ARRAY['Al-Alaq','Al-Falaq','Al-Nas','Al-Tin'], 0),
('Which companion was famous for their beautiful recitation and called “Sayyid al-Qurra”?', ARRAY['Ubayy ibn Ka’b','Bilal','Ali','Aisha'], 0),
('Which prophet had a dialect understood by jinn?', ARRAY['Sulayman','Musa','Isa','Ibrahim'], 0),
('What is the Arabic term for ritual slaughter of halal animals?', ARRAY['Halal','Dhabihah','Zakat','Jihad'], 1),
('What was the original Qiblah of the Muslims before it changed to the Kaaba?', ARRAY['Jerusalem','Makkah','Madinah','Taif'], 0),
('Who was the grandfather of Prophet Muhammad ﷺ?', ARRAY['Abdul Muttalib','Abu Talib','Hamza','Umar'], 0),
('Which Surah mentions the Battle of Badr explicitly by name?', ARRAY['Al-Imran','Al-Anfal','Al-Baqarah','Al-Nasr'], 1),
('What is the Arabic term for the minor pilgrimage that can be performed any time of the year?', ARRAY['Umrah','Hajj','Dua','Zakat'], 0),
('Which Sahabi was known as the “scribe of revelation” besides Zayd Ibn Thabit?', ARRAY['Ubayy ibn Ka’b','Ali','Umar','Uthman'], 0),
('In which Hijri year was alcohol prohibited in Islam?', ARRAY['2','3','4','5'], 2),
('Which Prophet’s miracle included softening iron?', ARRAY['Dawud','Musa','Isa','Ibrahim'], 0),
('What is the Surah that mentions both honey and milk in the context of a sign from Allah?', ARRAY['Al-Nahl','Al-Baqarah','Al-Mulk','Al-Fatiha'], 0),
('Which companion acted as the Prophet’s ﷺ translator for dealing with non-Arabs?', ARRAY['Zayd ibn Thabit','Bilal','Umar','Ali'], 0),
('Where did Prophet Musa عليه السلام speak directly with Allah?', ARRAY['Mount Sinai','Mount Uhud','Mount Thawr','Mount Hira'], 0),
('How many times is the name “Muhammad” mentioned in the Qur’an?', ARRAY['3','4','5','9'], 1),
('What is the term for the contract agreed upon during a marriage ceremony?', ARRAY['Nikah','Aqd','Mahr','Shahada'], 1),
('Which Surah starts without “Bismillah”?', ARRAY['At-Tawbah','Al-Fatiha','Al-Baqarah','Al-Kahf'], 0),
('How many authentic books make up the Kutub al-Sittah (Six Books of Hadith)?', ARRAY['6','7','10','9'], 0),
('Who was the last companion to die who participated in Badr?', ARRAY['Abu Tufail','Umar','Ali','Bilal'], 0),
('Which battle did Muslims fight without the Prophet ﷺ present?', ARRAY['Battle of Mutah','Battle of Hunayn','Battle of Uhud','Battle of Tabuk'], 0),
('Which wife of the Prophet ﷺ was the daughter of Abu Sufyan?', ARRAY['Umm Habibah','Sauda','Khadijah','Hafsa'], 0),
('Which Surah narrates the story of Prophet Sulayman and Queen Bilqis?', ARRAY['Al-Naml','Al-Falaq','Al-Kahf','Al-Mulk'], 0),
('Who was known as the “Mother of the Poor” among the wives of the Prophet ﷺ?', ARRAY['Zaynab bint Khuzaymah','Hafsa','Aisha','Khadijah'], 0),
('Which major Islamic empire ended with the Mongol invasion of Baghdad in 1258?', ARRAY['Abbasid','Umayyad','Ottoman','Fatimid'], 0),
('Which Surah contains the dua: “My Lord! Increase me in knowledge”?', ARRAY['Ta-Ha','Al-Fatiha','Al-Kahf','Al-Baqarah'], 0),
('Who was the Prophet ﷺ sent as a mercy to?', ARRAY['All creation','Muslims','Arabs','Angels'], 0),
('What is the Arabic name of the miraculous night journey from Masjid al-Haram to Masjid al-Aqsa?', ARRAY['Isra','Qiyam','Tarawih','Hijrah'], 0),
('What was the name of the treaty that allowed Muslims to peacefully perform Umrah later?', ARRAY['Hudaybiyyah','Aqabah','Taif','Medina'], 0),
('Who led the Muslim navy in the first Islamic sea battle?', ARRAY['Muawiyah ibn Abi Sufyan','Ali','Uthman','Abu Bakr'], 0),
('Which Surah was the last full Surah revealed?', ARRAY['Al-Nasr','Al-Falaq','Al-Baqarah','Al-Kahf'], 0),
('What is the Arabic term for a chapter in the Qur’an?', ARRAY['Ayah','Surah','Juz','Sunnah'], 1),
('In which battle did Hamza, the uncle of the Prophet ﷺ, become a martyr?', ARRAY['Uhud','Badr','Khandaq','Hunayn'], 0),
('Who was the mother of Prophet Ismail عليه السلام?', ARRAY['Hajar','Sarah','Aisha','Maryam'], 0),
('What are the two main Eids in Islam called?', ARRAY['Eid al-Fitr & Eid al-Adha','Eid Milad & Eid Ghadir','Eid Qurban & Eid Mubahala','Eid An-Nasr & Eid al-Tin'], 0),
('What illness caused the death of Prophet Muhammad ﷺ?', ARRAY['Fever','Malaria','Pneumonia','Heart disease'], 0),
('What is the place Muslims stand during Hajj to have their sins forgiven?', ARRAY['Arafat','Mina','Muzdalifah','Safā'], 0),
('Which two Prophets are called “brothers” and sent to the same people?', ARRAY['Musa & Harun','Isa & Yahya','Ibrahim & Lut','Yusuf & Binyamin'], 0),
('Which angel is the guardian of Hellfire?', ARRAY['Malik','Jibril','Azrael','Israfil'], 0),
('Who was the commander for the conquest of Persia during Umar’s caliphate?', ARRAY['Sa’d ibn Abi Waqqas','Khalid ibn al-Walid','Uthman','Ali'], 0),
('Which Surah mentions the rank of martyrs?', ARRAY['Al-Imran','Al-Baqarah','Al-Fatiha','Al-Anfal'], 0),
('Which Prophet was punished by losing his voice except for remembrance of Allah?', ARRAY['Zakariya','Musa','Ibrahim','Isa'], 0),
('Which Prophet was able to understand the speech of insects?', ARRAY['Sulayman','Musa','Yusuf','Nuh'], 0),
('Which battle is also called Ghazwat al-Furqan?', ARRAY['Badr','Uhud','Hunayn','Khandaq'], 0),
('Who compiled Imam Malik’s Muwatta?', ARRAY['Imam Malik','Zayd ibn Thabit','Uthman','Ali'], 0),
('In which Hijri year was zakat made obligatory?', ARRAY['2','1','3','9'], 0),
('What does the term “Ghusl” mean in Islamic jurisprudence?', ARRAY['Purification bath','Prayer','Charity','Wudu (ablution)'], 0),
('Which Sahabi was famous for his skill in medicine and treating wounds?', ARRAY['Rufaydah bint Sa’ad','Abu Bakr','Ali','Uthman'], 0),
('Which Surah mentions the story of Maryam in detail?', ARRAY['Maryam','Al-Fatiha','Al-Kahf','Al-Baqarah'], 0),
('Who was the first female scholar of Hadith among the Sahabiyyat?', ARRAY['Aisha','Fatimah','Khadijah','Maryam'], 0),
('What is the name of the plain where the Battle of Badr was fought?', ARRAY['Plain of Badr','Plain of Uhud','Plain of Hunayn','Plain of Mina'], 0),
('Which Prophet built a ship as commanded by Allah?', ARRAY['Nuh','Musa','Ibrahim','Isa'], 0),
('Which Surah frequently repeats the verse: “So which of the favors of your Lord will you deny?”', ARRAY['Al-Rahman','Al-Fatiha','Al-Baqarah','Al-Mulk'], 0),
('Which Prophet asked to see Allah but fainted when the mountain crumbled?', ARRAY['Musa','Isa','Ibrahim','Nuh'], 0),
('What is the Arabic term for things that break wudu?', ARRAY['Nawaqid','Makruh','Haram','Wajib'], 0),
('Who was the first to write the Mushaf during Abu Bakr’s reign?', ARRAY['Zayd ibn Thabit','Ali','Uthman','Umar'], 0),
('Which Surah narrates the story of the slander (Ifk) against Aisha رضي الله عنها?', ARRAY['Al-Nur','Al-Falaq','Al-Kahf','Al-Mulk'], 0),
('What is the Arabic term for purification of wealth through charity?', ARRAY['Tazkiyah','Zakat','Wudu','Salat'], 1),
('Who was the first person buried in Jannat al-Baqi?', ARRAY['Uthman','Ruqayyah bint Rasul','Ali','Usman bin Maz''un'], 3),
('Which Surah mentions the “Pen” as an oath?', ARRAY['Al-Qalam','Al-Baqarah','Al-Fatiha','Al-Kahf'], 0),
('Who was responsible for the hunger boycott against Muslims in Makkah?', ARRAY['Abu Jahl','Abu Lahab','Abu Sufyan','Umar'], 0),
('Which Prophet used to make dua when facing hardship: “La ilaha illa anta subhanaka inni kuntu mina’z-zalimeen”?', ARRAY['Yunus','Musa','Isa','Ibrahim'], 0),
('What is the Arabic term for unanimous agreement of scholars?', ARRAY['Ijma','Qiyas','Fiqh','Sunnah'], 0),
('Which Khalifah was known as “The Leader of the Faithful” first?', ARRAY['Umar','Ali','Abu Bakr','Uthman'], 0),
('What city was known as Yathrib before Islam?', ARRAY['Madinah','Makkah','Jerusalem','Baghdad'], 0),
('Which Surah offers protection from envy and witchcraft?', ARRAY['Al-Falaq','Al-Ikhlas','Al-Kahf','Al-Nas'], 0),
('When will the gates of repentance be closed forever?', ARRAY['Death','Day of Judgment','Sun rises from West','Maghrib'], 2),
('Which Sahabi was known for bravery and called “the Lion of Allah”?', ARRAY['Hamza','Ali','Umar','Bilal'], 0),
('What is the scale used on the Day of Judgment to weigh deeds called?', ARRAY['Mizaan','Sirat','Furqan','Tawhid'], 0),
('Which Prophet lost his children and wealth but remained extremely patient?', ARRAY['Ayyub','Yusuf','Musa','Sulayman'], 0),
('What is the Arabic term for the call to prayer?', ARRAY['Adhan','Takbir','Iqamah','Khutbah'], 0),
('During which battle did the Prophet’s ﷺ tooth get injured?', ARRAY['Uhud','Badr','Tabuk','Hunayn'], 0),
('Who will intercede for believers on the Day of Judgment by Allah’s permission?', ARRAY['Prophet Muhammad','Isa','Musa','Jibril'], 0),
('Which city was conquered without bloodshed during the Prophet’s ﷺ life?', ARRAY['Makkah','Jerusalem','Madinah','Taif'], 0),
('What is the name of the group that guarded the Prophet ﷺ at night until a Quranic verse removed the need?', ARRAY['Al-Muhajirun','Al-Ansar','Al-Mujahideen','Al-Layl'], 1),
('Which Sahabi was nicknamed the “scholar of this Ummah”?', ARRAY['Ibn Abbas','Ibn Umar','Ali','Uthman'], 0),
('What is the name of the well discovered by Ismail’s mother?', ARRAY['Zamzam','Quda','Tabuk','Rawha'], 0),
('Which Prophet’s miracle included softening iron?', ARRAY['Dawud','Musa','Isa','Yusuf'], 0),
('Which wife of the Prophet ﷺ was called “Mother of the Believers” and known for nursing orphans?', ARRAY['Umm Salama','Umm Habibah','Aisha','Khadijah'], 0),
('Which Surah begins with the letters “Taha”?', ARRAY['Ta-Ha','Al-Fatiha','Al-Baqarah','Al-Mulk'], 0),
('Which Prophet asked Allah to show him how resurrection happens?', ARRAY['Ibrahim','Isa','Musa','Muhammad'], 0),
('Which Surah contains rules about inheritance?', ARRAY['Al-Nisa','Al-Mulk','Al-Fajr','Al-Falaq'], 0),
('What is the first Surah revealed after the Prophet ﷺ migrated to Madinah?', ARRAY['Al-Baqarah','Al-Fatiha','Al-Nas','Al-Mulk'], 0),
('Which Prophet had the miracle of the camel as a sign?', ARRAY['Salih','Musa','Isa','Ibrahim'], 0),
('Who was the Prophet ﷺ’s only surviving child at his death?', ARRAY['Fatimah','Aisha','Zainab','Ruqayyah'], 0),
('What is the Arabic term for the major creed system of Islam based on Qur’an and Sunnah?', ARRAY['Aqidah','Jihad','Sunnah','Fiqh'], 0),
('Who narrated the majority of Hadith about Hajj?', ARRAY['Aisha','Ibn Umar','Abu Hurairah','Abu Bakr'], 1),
('Which Surah mentions the splitting of the moon as a miracle of the Prophet ﷺ?', ARRAY['Al-Qamar','Al-Falaq','Al-Kahf','Al-Mulk'], 0),
('What is the Arabic name for the divine tablet where everything is written?', ARRAY['Lawh Mahfuz','Aqidah','Sijjin','Tawhid'], 0),
('Which Khalifah established the Islamic calendar?', ARRAY['Umar ibn al-Khattab','Ali','Abu Bakr','Uthman'], 0),
('Which Surah begins with “Ar-Rahman”?', ARRAY['Ar-Rahman','Al-Fatiha','Al-Baqarah','Al-Mulk'], 0),
('Which Prophet was tested with a king who tried to take his wife?', ARRAY['Ibrahim','Musa','Isa','Yusuf'], 0),
('What is the ruling of praying on time in Islam?', ARRAY['Obligatory','Forbidden','Mustahab','Makruh'], 0),
('Which Sahabi was sent to destroy idols after the conquest of Makkah?', ARRAY['Khalid ibn al-Walid','Ali','Umar','Bilal'], 0),
('What were the tribes that fought in the Battle of Khandaq?', ARRAY['Quraysh & Allies','Ansar & Muhajirun','Aws & Khazraj','Jews & Christians'], 0),
('Which angel was responsible for the mountains?', ARRAY['Jibril','Mikail','Israfil','Azrael'], 0),
('Which wife of the Prophet ﷺ was known for her eloquence and knowledge of poetry?', ARRAY['Aisha','Hafsa','Zaynab bint Jahsh','Umm Salama'], 2),
('Which Sahabi narrated the Hadith of Jibril about Islam, Iman, and Ihsan?', ARRAY['Umar','Ali','Abu Bakr','Aisha'], 0),
('What city will Dajjal be unable to enter?', ARRAY['Makkah & Madinah','Jerusalem','Rome','Baghdad'], 0),
('Which Prophet miraculously healed his father’s eyesight?', ARRAY['Yusuf','Isa','Musa','Ibrahim'], 0),
('Which Surah is recommended to recite on Fridays?', ARRAY['Al-Kahf','Al-Fatiha','Al-Mulk','Al-Baqarah'], 0),
('What is the Arabic name for obligatory acts in prayer?', ARRAY['Fard','Sunnah','Wajib','Mustahab'], 0),
('Which Prophet faced constant opposition from his father and people because of idol worship?', ARRAY['Ibrahim','Musa','Isa','Sulayman'], 0),
('What is the name of the night when the Qur’an was first revealed?', ARRAY['Laylat al-Qadr','Laylat al-Baraat','Isra','Miraj'], 0),
('What are the four sacred months in Islam?', ARRAY['Muharram, Rajab, Dhul-Qa\'dah, Dhul-Hijjah', 'Ramadan, Shawwal, Muharram, Rajab', 'Rajab, Ramadan, Shawwal, Muharram', 'Shawwal, Rajab, Dhul-Qa\'dah, Dhul-Hijjah'], 0);
